### PR TITLE
Add CONTRIBUTING.md from https://github.com/kreteshq/kretes

### PR DESCRIPTION
**Pull request by Tuhaj**
Adds CONTRIBUTING.md from https://github.com/kreteshq/kretes

### CODE REVIEW

**Comment by zaiste** [comment]
@Tuhaj would you be up for rewriting the commits (by prepending the `docs`) as described in the CONTRIBUTING ? :)

**Comment by Tuhaj** [comment]
@zaiste now I can!
weye

**Comment by Tuhaj** [comment]
"This diagram shows an incorrect representation of the field of sight, and is taken from section 5.6331 of the Tractatus. The eye can be compared to the “I” which Wittgenstein is discussing in his argument. When we perceive things in our field of sight, we cannot actually see our own eye. All we are aware of is what we ourselves can see, this is true, but this does not give us any indication that the eye itself exists. The “I”, like the eye, is a limit of our world, but is not an object contained within it."
http://sweetprince.net/words/essays/wittgenstein%E2%80%99s-eye/ 😉

**Comment by Tuhaj** [comment]
@zaiste done !

**Pull request merged**
